In [36]:
import pandas as pd 
import numpy as np
import datetime as dt

In [ ]:
df_103 = pd.read_csv('SourceData/nst-est2017-alldata.csv', header = 0)
df_sub_103 = df_103.loc[df_103.DIVISION == '1',]
df_sub_103.set_index('NAME', inplace= True)
df_sub_103 = df_sub_103.loc[:,[i for i in df_sub_103.columns if i.startswith('POP')]]
df_sub_103

In [10]:
df_103_exc = pd.read_csv('data/2010YumaAZ.csv', header = 0)
df_103_exc

     LST_DATE      DAY LST_TIME  T_HR_AVG
0    20100601  TUESDAY     0:00      25.2
1    20100601  TUESDAY     1:00      24.1
2    20100601  TUESDAY     2:00      24.4
3    20100601  TUESDAY     3:00      24.9
4    20100601  TUESDAY     4:00      22.8
..        ...      ...      ...       ...
163  20100607   MONDAY    19:00      39.4
164  20100607   MONDAY    20:00      38.5
165  20100607   MONDAY    21:00      37.0
166  20100607   MONDAY    22:00      34.7
167  20100607   MONDAY    23:00      32.6

[168 rows x 4 columns]

In [11]:
df_104_exc = pd.read_csv('data/mocksurvey.csv', header = 0)
df_104_exc

,Unnamed: 0,Strongly Agree,Somewhat Agree,Neutral,Somewhat Disagree,Strongly Disagree
0,Question 1,0.45,0.25,0.10,0.12,0.08
1,Question 2,0.12,0.07,0.48,0.18,0.15
2,Question 3,0.05,0.22,0.19,0.23,0.31

In [13]:
df_104_exc.iloc[:,0]

0    Question 1
1    Question 2
2    Question 3
Name: Unnamed: 0, dtype: object

In [14]:
df_104_exc.iloc[0,1:]

Strongly Agree       0.45
Somewhat Agree       0.25
Neutral               0.1
Somewhat Disagree    0.12
Strongly Disagree    0.08
Name: 0, dtype: object

In [22]:
[print(df_104_exc.iloc[i,1:].index) for i in range(0,df_104_exc.shape[0])]

Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')
Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')
Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')

[None, None, None]

In [25]:
df_105 = pd.read_csv('data/mpg.csv', header = 0)
df_105

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [26]:
df_106 = pd.read_csv('data/abalone.csv', header = 0)
df_106

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
...,...,...,...,...,...,...,...,...,...
4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

In [ ]:
df_107_3  = pd.read_csv('/Users/pangrui/Desktop/Ploty_class/Plotly_udmy_class/Data/FremontBridgeBicycles.csv', header= 0)

df_107_3['Date'] = pd.to_datetime(df_107_3.Date)
df_107_3['new_date'] = df_107_3['Date'].dt.date
df_107_3['Hr'] = df_107_3['Date'].dt.time

df_107_3_final = df_107_3.groupby('Hr').agg({'Fremont Bridge West Sidewalk': 'sum', 'Fremont Bridge East Sidewalk': 'sum'}).reset_index()
df_107_3_final

          Hr  Fremont Bridge West Sidewalk  Fremont Bridge East Sidewalk
0   00:00:00                       10779.0                       13343.0
1   01:00:00                        5937.0                        6735.0
2   02:00:00                        4311.0                        4197.0
3   03:00:00                        3199.0                        2726.0
4   04:00:00                        7005.0                        5449.0
5   05:00:00                       33241.0                       17935.0
6   06:00:00                      116087.0                       63318.0
7   07:00:00                      303988.0                      141053.0
8   08:00:00                      406635.0                      215962.0
9   09:00:00                      220889.0                      146263.0
10  10:00:00                      109002.0                       82558.0
11  11:00:00                       92167.0                       74028.0
12  12:00:00                       95322.0                       81202.0
13  13:00:00                       99965.0                       89062.0
14  14:00:00                      104530.0                      100951.0
15  15:00:00                      123370.0                      136184.0
16  16:00:00                      170976.0                      253811.0
17  17:00:00                      240359.0                      498415.0
18  18:00:00                      190597.0                      327182.0
19  19:00:00                      103456.0                      150738.0
20  20:00:00                       63057.0                       83418.0
21  21:00:00                       42804.0                       51391.0
22  22:00:00                       28733.0                       34650.0
23  23:00:00                       18338.0                       23999.0

In [48]:
df_107_exc = pd.read_csv('data/abalone.csv')
df_107_exc.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [49]:
df_108_exc = pd.read_csv('data/iris.csv')
df_108_exc.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [51]:
df_109_exc = pd.read_csv('/Users/pangrui/Desktop/Ploty_class/Plotly_udmy_class/Data/flights.csv')
df_109_exc

     year      month  passengers
0    1949    January         112
1    1949   February         118
2    1949      March         132
3    1949      April         129
4    1949        May         121
..    ...        ...         ...
139  1960     August         606
140  1960  September         508
141  1960    October         461
142  1960   November         390
143  1960   December         432

[144 rows x 3 columns]

In [52]:
df_2_08 = pd.read_csv('data/gapminderDataFiveYear.csv', header= 0)
df_2_08

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [53]:
df_2_08.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   year       1704 non-null   int64
 2   pop        1704 non-null   float64
 3   continent  1704 non-null   object
 4   lifeExp    1704 non-null   float64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 80.0+ KB

In [55]:
df_2_08.year.drop_duplicates()

0     1952
1     1957
2     1962
3     1967
4     1972
5     1977
6     1982
7     1987
8     1992
9     1997
10    2002
11    2007
Name: year, dtype: int64

In [67]:
df_2_08.columns.values

array(['country', 'year', 'pop', 'continent', 'lifeExp', 'gdpPercap'],
      dtype=object)

In [68]:
data_2_11 = pd.DataFrame({'color': ['red', 'red', 'red', 'blue','blue','blue', 'yellow', 'yellow', 'yellow'],
             'value': [1,2,3,1,2,3,1,2,3]})
data_2_11

    color  value
0     red      1
1     red      2
2     red      3
3    blue      1
4    blue      2
5    blue      3
6  yellow      1
7  yellow      2
8  yellow      3

In [73]:
df_2_13 = pd.read_csv('data/wheels.csv', header = 0)
df_2_13.loc[df_2_13.color == 'red',].iloc[0,2]

'redunicycle.jpg'