In [1]:
import pandas as pd 
import numpy as np

In [ ]:
df_103 = pd.read_csv('SourceData/nst-est2017-alldata.csv', header = 0)
df_sub_103 = df_103.loc[df_103.DIVISION == '1',]
df_sub_103.set_index('NAME', inplace= True)
df_sub_103 = df_sub_103.loc[:,[i for i in df_sub_103.columns if i.startswith('POP')]]
df_sub_103

In [10]:
df_103_exc = pd.read_csv('data/2010YumaAZ.csv', header = 0)
df_103_exc

     LST_DATE      DAY LST_TIME  T_HR_AVG
0    20100601  TUESDAY     0:00      25.2
1    20100601  TUESDAY     1:00      24.1
2    20100601  TUESDAY     2:00      24.4
3    20100601  TUESDAY     3:00      24.9
4    20100601  TUESDAY     4:00      22.8
..        ...      ...      ...       ...
163  20100607   MONDAY    19:00      39.4
164  20100607   MONDAY    20:00      38.5
165  20100607   MONDAY    21:00      37.0
166  20100607   MONDAY    22:00      34.7
167  20100607   MONDAY    23:00      32.6

[168 rows x 4 columns]

In [11]:
df_104_exc = pd.read_csv('data/mocksurvey.csv', header = 0)
df_104_exc

,Unnamed: 0,Strongly Agree,Somewhat Agree,Neutral,Somewhat Disagree,Strongly Disagree
0,Question 1,0.45,0.25,0.10,0.12,0.08
1,Question 2,0.12,0.07,0.48,0.18,0.15
2,Question 3,0.05,0.22,0.19,0.23,0.31

In [13]:
df_104_exc.iloc[:,0]

0    Question 1
1    Question 2
2    Question 3
Name: Unnamed: 0, dtype: object

In [14]:
df_104_exc.iloc[0,1:]

Strongly Agree       0.45
Somewhat Agree       0.25
Neutral               0.1
Somewhat Disagree    0.12
Strongly Disagree    0.08
Name: 0, dtype: object

In [22]:
[print(df_104_exc.iloc[i,1:].index) for i in range(0,df_104_exc.shape[0])]

Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')
Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')
Index(['Strongly Agree', 'Somewhat Agree', 'Neutral', 'Somewhat Disagree',
       'Strongly Disagree'],
      dtype='object')

[None, None, None]