In [2]:
import numpy as np 
import pandas as pd 
import plotly.express as px 
import plotly.graph_objects as go 
import plotly.offline as pyo
import plotly.figure_factory as ff
import dash 
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output
import json
import base64

In [ ]:
upg = pd.read_csv('../data/mpg.csv', header = 0)
upg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [44]:
upg[:10]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,69.0,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,69.5,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,72.4,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,68.3,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70.0,1,ford torino
5,15.0,8,429.0,198,4341,10.0,71.2,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70.2,1,chevrolet impala
7,14.0,8,440.0,215,4312,8.5,70.2,1,plymouth fury iii
8,14.0,8,455.0,225,4425,10.0,69.8,1,pontiac catalina
9,15.0,8,390.0,190,3850,8.5,69.1,1,amc ambassador dpl

In [58]:
upd = dash.Dash()

upg['model_year'] = upg.model_year + np.random.randint(-4,5,upg.shape[0]) * 0.1

upd.layout = html.Div([
    html.Div([
        dcc.Graph(
            id = 'pt',
            figure={
                'data':[go.Scatter(x = upg.model_year +1900,
                                   y = upg.mpg,
                                   text= upg.name,
                                   hoverinfo = 'text',
                                   mode= 'markers')],

                'layout': go.Layout(title = 'MPG.CSV dataset',
                                    xaxis= dict(title = 'model year'),
                                    yaxis = dict(title = 'miles per gallon'), 
                                    hovermode = 'closest')

            }
        )
    ], style = dict(width = '50%', float = 'left', display = 'inline-block')), 
    html.Div([
        html.Div(id = 'hh', style= dict(color = 'white')),
        dcc.Graph(id = 'sub_p'),
        dcc.Markdown(id = 'mpg_stats'),
      html.Pre(id = 'sub_title', style = {'paddingTop': 35, 'color': 'white'}),
    ],  style=dict(width = '50%', float = 'right',  display = 'inline-block'))
])

@upd.callback(Output(component_id= 'sub_title', component_property= 'children'), 
              Input(component_id= 'pt', component_property= 'hoverData'))
def call_back_image(abc):
    return json.dumps(abc, indent = 2)

@upd.callback(Output(component_id= 'hh', component_property= 'children'), 
              Input(component_id= 'pt', component_property= 'hoverData'),
              prevent_initial_call=True)

def dis_text(abc):
    # point_d = abc['points'][0]['pointIndex']
    # tp1 = """ hello lloaa {}
    #         """.format(upg.iloc[point_d]['cylinders'])

    tp1 = f""" {abc['points'][0]['text']}"""
    return tp1

@upd.callback(Output(component_id= 'sub_p', component_property= 'figure'), 
              Input(component_id= 'pt', component_property= 'hoverData'),
              prevent_initial_call=True)

def insert_p(abc):
    print()
    t1 = upg.loc[upg.name == abc['points'][0]['text'], 'acceleration'].iloc[0]
    sub_d = [go.Scatter(x = [0,1],
                        y = [0, 60/t1],
                        mode = 'lines')]
    sty = go.Layout(margin = {'r': 0},
                    xaxis= dict(range=[0, 1],       # Sets the visible y-range
                                fixedrange=True,
                                visible=False),
                    yaxis= dict(range=[0, 5],       # Sets the visible y-range
                                fixedrange=True,
                                visible = False))
    
    return {'data': sub_d, 'layout': sty}


# upd.run()